version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/gargakshit/cg"

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  dialect = "typescript"
  module_system = "es-modules"

[[transformers]]
name = "gofumpt"
enabled = true

[[transformers]]
name = "prettier"
enabled = true